# Generated by Django 5.1 on 2025-12-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_rating_average_course_rating_count_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("science and technology", "Science and Technology"),
                    ("arts and crafts", "Arts and Crafts"),
                    ("reading and writing", "Reading and Writing"),
                    ("music and musical instruments", "Music and Musical Instruments"),
                    ("languages", "Languages"),
                    ("health and wellness", "Health and Wellness"),
                    ("business and finance", "Business and Finance"),
                    ("personal development", "Personal Development"),
                    ("other", "Other"),
                ],
                default="arts and crafts",
                max_length=100,
            ),
        ),
    ]
