# Generated by Django 5.1 on 2026-01-28 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_circlemeeting_circlemilestone_circlebadge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='join_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
